jetpack: jp6

default_release: r36.4.4

releases:

  r36.4.4:

    bsp:
      filename: Jetson_Linux_R36.4.4_aarch64.tbz2
      url: https://developer.download.nvidia.com/embedded/L4T/r36_Release_v4.4/release/Jetson_Linux_R36.4.4_aarch64.tbz2

    rootfs:
      filename: Tegra_Linux_Sample-Root-Filesystem_R36.4.4_aarch64.tbz2
      url: https://developer.download.nvidia.com/embedded/L4T/r36_Release_v4.4/release/Tegra_Linux_Sample-Root-Filesystem_R36.4.4_aarch64.tbz2

    sources:
      filename: public_sources.tbz2
      url: https://developer.download.nvidia.com/embedded/L4T/r36_Release_v4.4/sources/public_sources.tbz2